name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: site.yml
      - name: "Upload generated site"
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
